FROM ubuntu:latest

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  cmake g++ git clang build-essential gdb && \
  git config --global http.sslVerify false && \
  git clone https://github.com/AceRNorth/GeneralMetapop.git && \
  cd GeneralMetapop && \
  mkdir build && \
  cd build && \
  cmake .. && \
  cmake --build .
  
